services:
  docs:
    image: financial_tracker_local_docs
    container_name: financial_tracker_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./financial_tracker:/app/financial_tracker:z
    ports:
      - '9000:9000'
    command: /start-docs
