from rest_framework.routers import DefaultRouter
from django.urls import path
from .api.views import CurrencyViewSet, ExchangeRateViewSet, GetLocalCurrencyAPIView

router = DefaultRouter()
#router.register('', CurrencyViewSet, basename='currency')
router.register('currencies', CurrencyViewSet, basename='currency')
router.register('exchangerates', ExchangeRateViewSet, basename='exchangerate')
#router.register('currencies/exchangerates', ExchangeRateViewSet, basename='exchangerate')
app_name = "currencies"

urlpatterns = router.urls

urlpatterns = [
    *router.urls,  # Include URLs generated by the router
    path('get-localcurrency/', GetLocalCurrencyAPIView.as_view(), name='get-localcurrency'),
]




# urlpatterns = [
#     *router.urls,
#     path('currencies/get-localcurrency/', GetLocalCurrencyAPIView.as_view(), name='get-localcurrency'),
# ]
